config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  get '/auth/facebook', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', as: :logout, to: 'sessions#destroy'

  get '/profile', to: 'users#show'

  get '/autocomplete', to: 'google/autocomplete#index'
  get '/search', to: 'google/search#index'

  get "places/:slug", as: 'place', to: 'places#show'
  resources 'places', only: [:create]

  resources 'comments', only: [:create, :index]
  get "/comments/destroy", to: "comments#destroy"

  post '/follow', to: 'user_follows#create'
  get '/follow', to: 'user_follows#show'
  delete '/follow', to: 'user_follows#destroy'

  resources 'votes', only: [:create]
end

app/views/layouts/_comment.html.erb
<div id="standard-comment" class="sixteen wide column">
    <div id="comment-container" class="ui centered grid">
        <div id="votes" class="two wide center aligned column">
          <i id="<%= comment.id %>" class="chevron large up icon upvote"></i>
          <i id="<%= comment.id %>" class="chevron large down icon downvote"></i>
        </div>
        <div id="text-container" class="fourteen wide <%= comment.sentiment %> column">
          <h4 class="inline num"><%= votes(comment) %></h4>
            <p id="comment-text" class="inline">
                <%= comment.body %>
            </p>
        </div>
    </div>
</div>

app/views/layouts/_follow.html.erb
<%= link_to place_path(follow.slug), class: "sixteen wide center aligned column", id: "follow-text-container" do %>
    <div id="standard-follow">
         <h3 class="followable"><%= follow.name %></h3>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<% cache("footer") do %>
    <div class="ui center aligned inverted vertical footer segment">
        <div class="ui center aligned container">
            <div class="ui horizontal inverted small divided link list">
                <a class="item" href="#">Site Map</a>
                <a class="item" href="#">Contact Us</a>
                <a class="item" href="#">Terms and Conditions</a>
                <a class="item" href="#">Privacy Policy</a>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_messages.html.erb
<div id="messages", class="ui small modal">
  <div id="message-container" class="ui center aligned segment">
      <h3 id="the-message"><%= flash[:message] %></h3>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar" class="ui fixed inverted large menu">
    <%= link_to "FeedBee", root_path, class: "large item" %>
    <div class="right menu">
        <div id='nav-search' class = 'item'>
            <div class="ui search">
                <div class="ui icon mini input">
                    <%= form_tag("/places", method: "post") do %>
                      <input id="nav-search" name="go_to" class="prompt" type="text" placeholder="Search for something!">
                      <%= submit_tag "Go", class: "ui mini button" %>
                    <% end %>
                </div>
                <div class="results"></div>
            </div>
        </div><!--Search-->

      <% if current_user %>
        <%= link_to "Hello, #{current_user.name}", profile_path, class: "item" %>
        <%= link_to "Log Out", logout_path, class: "item" %>
      <% else %>
        <%= link_to "Log In with Facebook", login_path, class: "item" %>
        <a class="item">Sign Up</a>
      <% end %>
    </div>
</div>

app/views/layouts/_new_comment.html.erb
<div id='comment-form' class="twelve wide column">
    <%= form_for @comment, html: {class: "ui fluid left icon input", id: 'new-comment'} do |f| %>
        <i class="plus icon"></i>
        <%= f.text_field :body, id: "input-comment", placeholder: "Add a new comment" %>
        <%= f.hidden_field :commentable_id, :value => @presenter.id %>
        <%= f.hidden_field :commentable_type, :value => @presenter.class %>
        <%= f.hidden_field :sentiment, id: "sentiment" %>
          <div id="sentiment-button"> <%= f.submit "Submit", class: "ui button", id: "submit-button" %> </div>
          <div class="ui popup bottom left transition hidden" style="top: 154px; left: 1px; bottom: auto; right: auto; width: 761px;">
            <div class="ui relaxed divided grid">
              <div class="twelve wide column">
                <h4 class="ui header">Is your comment a good or bad thing?</h4>
                <div class="ui horizontal list">
                  <button id="good" class="mini ui green button">Good</a>
                  <button id="bad" class="mini ui red button">Bad</a>
                </div>
              </div>
            </div>
          </div>
    <% end  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeedBee</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>

    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  </head>
  <body class="fullscreen">
    <%= render "layouts/navbar" %>
    <%= render "layouts/messages" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>